# Copyright (c) 2021 Nick Winans
# SPDX-License-Identifier: MIT

CONFIG_ZMK_IDLE_TIMEOUT=120000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
# nkro
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# ZMK Studio 配置
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# 启用 USB 设备栈（会包含 CDC_ACM）
CONFIG_USB_DEVICE_STACK=y

# 强制开启电量上报
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# QMK/Vial 迁移键位包含鼠标按键、移动和滚轮层
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
